;;; elisp-dev-mcp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elisp-dev-mcp.el

(autoload 'elisp-dev-mcp-enable "elisp-dev-mcp" "\
Enable the Elisp development MCP tools.")
(autoload 'elisp-dev-mcp-disable "elisp-dev-mcp" "\
Disable the Elisp development MCP tools.")
(register-definition-prefixes "elisp-dev-mcp" '("elisp-dev-mcp--"))


;;; Generated autoloads from elisp-dev-mcp-test.el

(register-definition-prefixes "elisp-dev-mcp-test" '("elisp-dev-mcp-test-"))


;;; Generated autoloads from elisp-dev-mcp-sample-functions.el

(register-definition-prefixes "elisp-dev-mcp-sample-functions" '("elisp-dev-mcp-sample-with"))


;;; Generated autoloads from elisp-dev-mcp-test-fns.el

(register-definition-prefixes "elisp-dev-mcp-test-fns" '("elisp-dev-mcp-test-fns-with"))


;;; Generated autoloads from flycheck_elisp-dev-mcp.el

(autoload 'elisp-dev-mcp-enable "flycheck_elisp-dev-mcp" "\
Enable the Elisp development MCP tools.")
(autoload 'elisp-dev-mcp-disable "flycheck_elisp-dev-mcp" "\
Disable the Elisp development MCP tools.")
(register-definition-prefixes "flycheck_elisp-dev-mcp" '("elisp-dev-mcp--"))


;;; Generated autoloads from flycheck_elisp-dev-mcp-test.el

(register-definition-prefixes "flycheck_elisp-dev-mcp-test" '("elisp-dev-mcp-test-"))


;;; Generated autoloads from direct-test.el

(register-definition-prefixes "direct-test" '("elisp-dev-mcp-test-custom-var"))


;;; Generated autoloads from fix-debug.el

(register-definition-prefixes "fix-debug" '("debug-variable-description"))


;;; Generated autoloads from fix-proposal.el

(register-definition-prefixes "fix-proposal" '("elisp-dev-mcp-test-custom-var" "test-"))


;;; Generated autoloads from mock-test.el

(register-definition-prefixes "mock-test" '("elisp-dev-mcp--describe-variable" "mcp-tool-throw" "print-diagnostic" "test-custom-var"))


;;; Generated autoloads from simple-test.el

(register-definition-prefixes "simple-test" '("print-diagnostic" "test-custom-var"))


;;; Generated autoloads from test-internals.el

(register-definition-prefixes "test-internals" '("elisp-dev-mcp-" "mcp-"))


;;; Generated autoloads from test-parser.el

(register-definition-prefixes "test-parser" '("mcp-tool-throw" "test-"))


;;; Generated autoloads from debug-alias.el

(register-definition-prefixes "debug-alias" '("debug-get-function-definition" "json-encode-pretty" "local-test-alias" "test-alias"))


;;; Generated autoloads from get-if-response.el

(register-definition-prefixes "get-if-response" '("get-if-definition-response"))

;;; End of scraped data

(provide 'elisp-dev-mcp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elisp-dev-mcp-autoloads.el ends here
