;;; elisp-dev-mcp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elisp-dev-mcp.el

(autoload 'elisp-dev-mcp-enable "elisp-dev-mcp" "\
Enable the Elisp development MCP tools.")
(autoload 'elisp-dev-mcp-disable "elisp-dev-mcp" "\
Disable the Elisp development MCP tools.")
(register-definition-prefixes "elisp-dev-mcp" '("elisp-dev-mcp--"))


;;; Generated autoloads from elisp-dev-mcp-test.el

(register-definition-prefixes "elisp-dev-mcp-test" '("elisp-dev-mcp-test-"))


;;; Generated autoloads from flycheck_elisp-dev-mcp.el

(autoload 'elisp-dev-mcp-enable "flycheck_elisp-dev-mcp" "\
Enable the Elisp development MCP tools.")
(autoload 'elisp-dev-mcp-disable "flycheck_elisp-dev-mcp" "\
Disable the Elisp development MCP tools.")
(register-definition-prefixes "flycheck_elisp-dev-mcp" '("elisp-dev-mcp--"))



;;; Generated autoloads from debug-describe.el

(register-definition-prefixes "debug-describe" '("test-"))


;;; Generated autoloads from elisp-dev-mcp-test-no-checkdoc.el

(register-definition-prefixes "elisp-dev-mcp-test-no-checkdoc" '("elisp-dev-mcp-test-no-checkdoc--"))


;;; Generated autoloads from flycheck_elisp-dev-mcp-test.el

(register-definition-prefixes "flycheck_elisp-dev-mcp-test" '("elisp-dev-mcp-test-"))


;;; Generated autoloads from elisp-dev-mcp-test-dynamic.el

(register-definition-prefixes "elisp-dev-mcp-test-dynamic" '("elisp-dev-mcp-test-dynamic--with-header-comment"))


;;; Generated autoloads from elisp-dev-mcp-test-bytecode.el

(register-definition-prefixes "elisp-dev-mcp-test-bytecode" '("elisp-dev-mcp-test-bytecode--"))


;;; End of scraped data

(provide 'elisp-dev-mcp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elisp-dev-mcp-autoloads.el ends here
